# Generated by Django 4.2.7 on 2024-01-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Mobile', models.BigIntegerField()),
                ('Concern', models.CharField(max_length=40)),
                ('Help', models.CharField(max_length=40)),
                ('YourFeedback', models.CharField(max_length=40)),
            ],
        ),
    ]
