# Generated by Django 4.2.7 on 2024-01-07 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0002_clientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='mobile',
            field=models.CharField(help_text='Enter a 10-digit mobile number starting with 6, 7, 8, or 9.', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
