# Generated by Django 4.2.7 on 2024-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0003_alter_clientdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
