# Generated by Django 4.2.7 on 2024-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0004_alter_clientdata_mobile_alter_clientfeedback_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedback',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
