# Generated by Django 4.2.7 on 2024-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0005_remove_clientfeedback_mobile_clientdata_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
