# Generated by Django 4.2.7 on 2024-01-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0006_alter_clientdata_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
