# Generated by Django 4.2.7 on 2024-01-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0007_alter_clientdata_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='admin_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
