# Generated by Django 4.2.7 on 2024-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisfeedbackapp', '0008_clientdata_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='admin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
